### ISSUE TITLE
Leaving out the broker attribute in the connect tag should default to connecting to all brokers

### ISSUE THREAD

**Issue by sbaier1** [mqtt-varroa/varroa#143]
IMO this should be the default behavior, as most users will likely want to connect all of the clients to all of the brokers regardless.

This will also make programmatical substitution of the brokers easier, as there  is no need for referencing the brokers directly in the scenario

**Comment by sbaier1** [comment]
@sauroter @SgtSilvio what do you think?

**Comment by sauroter** [comment]
I like it
