### ISSUE TITLE
Make clientIdPattern in clientGroup optional and use a default pattern

### ISSUE THREAD

**Issue by MicWalter** [mqtt-varroa/varroa#150]
**Motivation:**
Sometimes the client id pattern for a client group is not needed. A default pattern would suffice.

**Problem:**
For every clientGroup a clientIdPattern is required, even if the client id pattern is of no interest in the test.

**Solution:**
Use a default clientIdPattern and make definition of clientIdPattern optional.
To make sure the default pattern doesn't collision with that of other clientGroups the clientGroup id could be used as a prefix (as the clientGroup id has to be unique)

**Example:**
`<clientGroup id="publisher">
            <count>10</count>
  </clientGroup>
  <clientGroup id="subscriber1">
            <count>10</count>
  </clientGroup>`

**Example Result:**
publisher-00000000001
....
publisher-00000000010
subscriber1-00000000001
....
subscriber1-00000000010

**Comment by YannickWeber** [comment]
good idea 👍

**Comment by YannickWeber** [comment]
implemented with[PR#150](https://github.com/mqtt-varroa/varroa/pull/155)
