### ISSUE TITLE
connect tag needs max timeout and wait for ack options

### ISSUE THREAD

**Issue by sbaier1** [mqtt-varroa/varroa#152]
While inspecting #144 it was discovered that there is some confusing behavior when the MqttAgents fail to connect due to an incorrect broker address or service/network failure leading to TCP timeouts.

This can lead to short stages taking a very long time to continue and therefore we should add
A maximum timeout attribute to the connect tag, to specify a maximum time before Varroa will continue with the next item in a lifecycle. This attribute should come with a sane default so the confusing behavior does not arise in normal usage anymore.

**Comment by YannickWeber** [comment]
implemented: [PR#154](https://github.com/mqtt-varroa/varroa/pull/154)
